# Generated by Django 4.0.4 on 2022-06-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_label', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagecategory',
            name='image_path',
            field=models.ImageField(upload_to=''),
        ),
    ]
