# Generated by Django 4.0.4 on 2022-06-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_label', '0002_alter_image_path_alter_imagecategory_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='answer_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
