# Generated by Django 4.0.4 on 2022-06-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_label', '0003_alter_image_answer_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='imagecategory',
            name='question',
            field=models.TextField(),
        ),
    ]
