# Generated by Django 4.0.4 on 2022-06-17 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_label', '0004_alter_imagecategory_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageCategory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_category',
            new_name='category',
        ),
    ]
