# Generated by Django 4.0.4 on 2022-06-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_label', '0005_userscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='verified',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
