# Generated by Django 4.0.4 on 2022-06-20 09:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_label', '0006_image_verified'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='ImageLabel',
            new_name='UserAnswer',
        ),
    ]
