# Generated by Django 4.0.4 on 2022-05-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question', models.TextField()),
                ('image_url', models.TextField()),
                ('language', models.CharField(max_length=15)),
                ('question_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fact', models.IntegerField(choices=[('0', 'Not sure'), ('1', 'Yes'), ('2', 'No'), ('3', 'skip')])),
                ('user_id', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
