# Generated by Django 4.0.4 on 2022-05-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='user_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
