# Generated by Django 4.0.4 on 2022-05-27 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_response_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='fact',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
