# Generated by Django 4.0.4 on 2022-06-02 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('top_img_url', models.TextField()),
                ('bottom_img_url', models.TextField()),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CompareAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(choices=[(0, 'Top'), (1, 'Bottom'), (2, 'Similar'), (3, 'Skip')])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compareAnswers', to='food_compare.comparequestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compareAnswers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
