# Generated by Django 4.0.4 on 2022-06-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_compare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparequestion',
            name='response_count',
            field=models.IntegerField(default=0),
        ),
    ]
