# Generated by Django 4.0.4 on 2022-06-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_compare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compareanswer',
            name='answer',
            field=models.CharField(choices=[('0', 'Top'), ('1', 'Bottom'), ('2', 'Similar'), ('3', 'Skip')], max_length=2),
        ),
    ]
