# Generated by Django 4.0.4 on 2022-06-04 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_compare', '0002_alter_compareanswer_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('0', 'Top'), ('1', 'Bottom'), ('2', 'Similar'), ('3', 'Skip')], max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='comparequestion',
            name='bottom_img_url',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='comparequestion',
            name='top_img_url',
            field=models.ImageField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='CompareAnswer',
        ),
        migrations.AddField(
            model_name='comparison',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comparison', to='food_compare.comparequestion'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comparison', to=settings.AUTH_USER_MODEL),
        ),
    ]
