# Generated by Django 4.0.4 on 2022-06-06 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_compare', '0002_comparequestion_response_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparequestion',
            name='response_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
