# Generated by Django 4.0.4 on 2022-06-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_compare', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='default.jpg', upload_to='profile_images'),
        ),
    ]
