# Generated by Django 4.0.4 on 2022-06-12 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_compare', '0006_profile_profile_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
