# Generated by Django 4.0.4 on 2022-06-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_compare', '0009_profile_bio_profile_birthday_profile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
