# Generated by Django 4.0.4 on 2022-06-05 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('language', models.CharField(max_length=20)),
                ('number_of_answers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluatedSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('0', 'Previous'), ('1', 'Negative'), ('2', 'Neutral'), ('3', 'Positive'), ('4', 'Skip')], max_length=2)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluatedSentiments', to='sentiment.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluatedSentiments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
