# Generated by Django 4.0.4 on 2022-06-07 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sentiment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluatedsentiment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluated_sentiments', to='sentiment.question'),
        ),
        migrations.AlterField(
            model_name='evaluatedsentiment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluated_sentiments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluatedsentiment',
            name='value',
            field=models.CharField(choices=[('previous', 'Previous'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('positive', 'Positive'), ('skip', 'Skip')], max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='number_of_answers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
