# Generated by Django 4.0.5 on 2022-06-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('language', models.CharField(max_length=20)),
                ('number_of_sent_answers', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
