# Generated by Django 4.0.5 on 2022-06-10 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('img_url', models.ImageField(upload_to='')),
                ('question', models.TextField()),
                ('response_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('0', 'Top'), ('1', 'Bottom'), ('2', 'Similar'), ('3', 'Skip')], max_length=2)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Response', to='food_fact.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Response', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
