# Generated by Django 4.0.5 on 2022-06-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_fact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.CharField(choices=[('0', 'yes'), ('1', 'no'), ('2', 'not sure'), ('3', 'Skip')], max_length=2),
        ),
    ]
