# Generated by Django 4.0.5 on 2022-06-11 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_fact', '0002_alter_response_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='img_url',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Response', to='food_fact.question'),
        ),
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.CharField(blank=True, choices=[('0', 'Yes'), ('1', 'No'), ('2', 'Not Sure'), ('3', 'Skip')], max_length=2),
        ),
        migrations.AlterField(
            model_name='response',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Response', to=settings.AUTH_USER_MODEL),
        ),
    ]
