# Generated by Django 4.0.5 on 2022-06-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_fact', '0003_alter_question_img_url_alter_question_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='img_url',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(),
        ),
    ]
