# Generated by Django 4.0.4 on 2022-06-12 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_fact', '0004_alter_question_id_alter_question_img_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Response', to='food_fact.question'),
        ),
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.CharField(choices=[('0', 'Yes'), ('1', 'No'), ('2', 'Not Sure'), ('3', 'Skip')], max_length=2),
        ),
        migrations.AlterField(
            model_name='response',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Response', to=settings.AUTH_USER_MODEL),
        ),
    ]
