# Generated by Django 4.0.5 on 2022-06-13 10:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_fact', '0005_alter_response_question_alter_response_response_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='QuestionModel',
        ),
        migrations.RenameModel(
            old_name='Response',
            new_name='ResponseModel',
        ),
    ]
