# Generated by Django 4.0.5 on 2022-06-19 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_fact', '0006_rename_question_questionmodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionModel',
            new_name='Question',
        ),
    ]
