# Generated by Django 4.0.5 on 2022-06-19 08:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_fact', '0007_rename_questionmodel_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResponseModel',
            new_name='answer',
        ),
    ]
