# Generated by Django 4.0.4 on 2022-06-19 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('language', models.CharField(max_length=20)),
                ('number_of_sent_answers', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluatedTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('skip', 'skip'), ('true', 'true'), ('false', 'false')], max_length=10)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluated_translation', to='translation_evaluator.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluated_translation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
