# Generated by Django 4.0.4 on 2022-06-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_evaluator', '0002_alter_evaluatedtranslation_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluatedtranslation',
            name='value',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (3, 'Skipped')]),
        ),
    ]
